### PR TITLE
Updated to autoprefix from compass

### PR DESCRIPTION
**Pull request by kayluhb**
Compass is dead. Long live autoprefixer.
- Updates grunt script to auto-load tasks
- Updates the grunt script to use autoprefixer instead of compass since compass is no longer in active development.  Also, autoprefixer is much easier.
- Adds a linter for scss and fixes a lot of scss lints.

### CODE REVIEW

**Comment by irsalmashhor** [comment]
Hi Caleb,

With these changes, does this mean we need to install the npm / grunt environment and do a grunt:watch ? 

Does this change the sass compilation process that we used to have and will it impact deployment as well?

**Comment by kayluhb** [comment]
No, npm and grunt won't be necessary to use the sass in this boilerplate.  Npm/grunt has been a part of the root level of this repo for a while to build the sass to the static stylesheet, which hasn't actually been used for a while in projects (AFAIK), it's just there for testing the default styles in this repo.

The only implication moving forward with this change is the references to compass have been removed and it is now recommended to use autoprefixer in future projects instead of compass.  Autoprefixer works similarly to how compass was used in rails/django/etc and it takes about 2 seconds to get going.  I've got it running on licp already with django-compressor-autoprefixer.  Autoprefixer with django may have a node dependency though, but I can confirm later if that's an issue.

**Comment by irsalmashhor** [comment]
Ok that sounds good! Thanks for keeping us honest and up to date!

**Comment by kayluhb** [comment]
👍 thanks for reviewing!

**Pull request merged**
